[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "gcc",
  "zlib.dev",
  "libxml2.dev",
  "libffi.dev",
  "openssl.dev",
  "stdenv.cc.cc.lib",
  "glibcLocales"
]

[phases.build]
cache = false  # Nix handles caching automatically
commands = [
  # Clean any Python remnants
  "rm -rf ~/.cache/pip ~/.local/lib/python3*",
  
  # Install directly into Nix store
  "pip install --prefix=/nix/store torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu",
  "pip install --prefix=/nix/store -r requirements.txt",
  
  # Create symlinks for runtime
  "ln -s /nix/store/lib/python3.10/site-packages /app/site-packages"
]

[phases.start]
command = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"