[phases.setup]
nixPkgs = [
  "python310",
  "gcc",
  "zlib.dev",
  "zlib",  # Explicit zlib library
  "libxml2.dev",
  "libffi.dev",
  "openssl.dev",
  "stdenv.cc.cc.lib"  # C library dependencies
]

[phases.build]
commands = [
  "pip install --upgrade pip setuptools wheel",
  "pip install torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu",
  "pip install -r requirements.txt"
]

[phases.start]
command = "uvicorn main:app --host 0.0.0.0 --port $PORT"