[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "gcc",
  "zlib.dev",
  "libxml2.dev",
  "libffi.dev",
  "openssl.dev",
  "glibc",
  "stdenv.cc.cc.lib",
  "linuxHeaders"
]

[phases.build]
commands = [
  "pip install --upgrade pip setuptools wheel",
  "pip install torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu --no-cache-dir",
  "pip install -r requirements.txt --no-cache-dir --use-pep517"
]
