[phases.setup]
nixPkgs = [
  "python310",
  "gcc",
  "zlib.dev",
  "libxml2.dev",
  "libffi.dev",
  "openssl.dev",
  "stdenv.cc.cc.lib",
  "glibcLocales"
]

[phases.build]
commands = [
  # Clean any existing Python installations
  "rm -rf /opt/venv ~/.cache/pip ~/.local/lib/python3*",
  
  # Install directly using Nix-managed Python
  "pip install --user --upgrade pip setuptools wheel",
  "pip install --user torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu",
  "pip install --user -r requirements.txt"
]

[phases.start]
command = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"